queue_rules:
  - name: default
    conditions:
      - "#approved-reviews-by>=1"

pull_request_rules:
  - name: automerge to main with label automerge and branch protection passing
    conditions:
      - "#approved-reviews-by>=1"
      - base=main
      - label=merge me daddy
    actions:
      queue:
        name: default
        method: squash
        commit_message_template: |
          {{ title }} (#{{ number }})
          {{ body }}
  - name: backport patches to v0.0.2-alpha branch
    conditions:
      - base=main
      - label=backport/v0.0.2-alpha
    actions:
      backport:
        branches:
          - release/v0.0.2-alpha
