// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/ethereum/go-ethereum/core/types"
	"pkg.berachain.dev/polaris/eth/core"
	"sync"
)

// Ensure, that BlockPluginMock does implement core.BlockPlugin.
// If this is not the case, regenerate this file with moq.
var _ core.BlockPlugin = &BlockPluginMock{}

// BlockPluginMock is a mock implementation of core.BlockPlugin.
//
//	func TestSomethingThatUsesBlockPlugin(t *testing.T) {
//
//		// make and configure a mocked core.BlockPlugin
//		mockedBlockPlugin := &BlockPluginMock{
//			BaseFeeFunc: func(contextMoqParam context.Context) uint64 {
//				panic("mock out the BaseFee method")
//			},
//			GetHeaderByNumberFunc: func(contextMoqParam context.Context, n int64) (*types.Header, error) {
//				panic("mock out the GetHeaderByNumber method")
//			},
//			NewHeaderWithBlockNumberFunc: func(contextMoqParam context.Context, n int64) *types.Header {
//				panic("mock out the NewHeaderWithBlockNumber method")
//			},
//			SetHeaderByNumberFunc: func(contextMoqParam context.Context, n int64, header *types.Header) error {
//				panic("mock out the SetHeaderByNumber method")
//			},
//		}
//
//		// use mockedBlockPlugin in code that requires core.BlockPlugin
//		// and then make assertions.
//
//	}
type BlockPluginMock struct {
	// BaseFeeFunc mocks the BaseFee method.
	BaseFeeFunc func(contextMoqParam context.Context) uint64

	// GetHeaderByNumberFunc mocks the GetHeaderByNumber method.
	GetHeaderByNumberFunc func(contextMoqParam context.Context, n int64) (*types.Header, error)

	// NewHeaderWithBlockNumberFunc mocks the NewHeaderWithBlockNumber method.
	NewHeaderWithBlockNumberFunc func(contextMoqParam context.Context, n int64) *types.Header

	// SetHeaderByNumberFunc mocks the SetHeaderByNumber method.
	SetHeaderByNumberFunc func(contextMoqParam context.Context, n int64, header *types.Header) error

	// calls tracks calls to the methods.
	calls struct {
		// BaseFee holds details about calls to the BaseFee method.
		BaseFee []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
		}
		// GetHeaderByNumber holds details about calls to the GetHeaderByNumber method.
		GetHeaderByNumber []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// N is the n argument value.
			N int64
		}
		// NewHeaderWithBlockNumber holds details about calls to the NewHeaderWithBlockNumber method.
		NewHeaderWithBlockNumber []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// N is the n argument value.
			N int64
		}
		// SetHeaderByNumber holds details about calls to the SetHeaderByNumber method.
		SetHeaderByNumber []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// N is the n argument value.
			N int64
			// Header is the header argument value.
			Header *types.Header
		}
	}
	lockBaseFee                  sync.RWMutex
	lockGetHeaderByNumber        sync.RWMutex
	lockNewHeaderWithBlockNumber sync.RWMutex
	lockSetHeaderByNumber        sync.RWMutex
}

// BaseFee calls BaseFeeFunc.
func (mock *BlockPluginMock) BaseFee(contextMoqParam context.Context) uint64 {
	if mock.BaseFeeFunc == nil {
		panic("BlockPluginMock.BaseFeeFunc: method is nil but BlockPlugin.BaseFee was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
	}{
		ContextMoqParam: contextMoqParam,
	}
	mock.lockBaseFee.Lock()
	mock.calls.BaseFee = append(mock.calls.BaseFee, callInfo)
	mock.lockBaseFee.Unlock()
	return mock.BaseFeeFunc(contextMoqParam)
}

// BaseFeeCalls gets all the calls that were made to BaseFee.
// Check the length with:
//
//	len(mockedBlockPlugin.BaseFeeCalls())
func (mock *BlockPluginMock) BaseFeeCalls() []struct {
	ContextMoqParam context.Context
} {
	var calls []struct {
		ContextMoqParam context.Context
	}
	mock.lockBaseFee.RLock()
	calls = mock.calls.BaseFee
	mock.lockBaseFee.RUnlock()
	return calls
}

// GetHeaderByNumber calls GetHeaderByNumberFunc.
func (mock *BlockPluginMock) GetHeaderByNumber(contextMoqParam context.Context, n int64) (*types.Header, error) {
	if mock.GetHeaderByNumberFunc == nil {
		panic("BlockPluginMock.GetHeaderByNumberFunc: method is nil but BlockPlugin.GetHeaderByNumber was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		N               int64
	}{
		ContextMoqParam: contextMoqParam,
		N:               n,
	}
	mock.lockGetHeaderByNumber.Lock()
	mock.calls.GetHeaderByNumber = append(mock.calls.GetHeaderByNumber, callInfo)
	mock.lockGetHeaderByNumber.Unlock()
	return mock.GetHeaderByNumberFunc(contextMoqParam, n)
}

// GetHeaderByNumberCalls gets all the calls that were made to GetHeaderByNumber.
// Check the length with:
//
//	len(mockedBlockPlugin.GetHeaderByNumberCalls())
func (mock *BlockPluginMock) GetHeaderByNumberCalls() []struct {
	ContextMoqParam context.Context
	N               int64
} {
	var calls []struct {
		ContextMoqParam context.Context
		N               int64
	}
	mock.lockGetHeaderByNumber.RLock()
	calls = mock.calls.GetHeaderByNumber
	mock.lockGetHeaderByNumber.RUnlock()
	return calls
}

// NewHeaderWithBlockNumber calls NewHeaderWithBlockNumberFunc.
func (mock *BlockPluginMock) NewHeaderWithBlockNumber(contextMoqParam context.Context, n int64) *types.Header {
	if mock.NewHeaderWithBlockNumberFunc == nil {
		panic("BlockPluginMock.NewHeaderWithBlockNumberFunc: method is nil but BlockPlugin.NewHeaderWithBlockNumber was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		N               int64
	}{
		ContextMoqParam: contextMoqParam,
		N:               n,
	}
	mock.lockNewHeaderWithBlockNumber.Lock()
	mock.calls.NewHeaderWithBlockNumber = append(mock.calls.NewHeaderWithBlockNumber, callInfo)
	mock.lockNewHeaderWithBlockNumber.Unlock()
	return mock.NewHeaderWithBlockNumberFunc(contextMoqParam, n)
}

// NewHeaderWithBlockNumberCalls gets all the calls that were made to NewHeaderWithBlockNumber.
// Check the length with:
//
//	len(mockedBlockPlugin.NewHeaderWithBlockNumberCalls())
func (mock *BlockPluginMock) NewHeaderWithBlockNumberCalls() []struct {
	ContextMoqParam context.Context
	N               int64
} {
	var calls []struct {
		ContextMoqParam context.Context
		N               int64
	}
	mock.lockNewHeaderWithBlockNumber.RLock()
	calls = mock.calls.NewHeaderWithBlockNumber
	mock.lockNewHeaderWithBlockNumber.RUnlock()
	return calls
}

// SetHeaderByNumber calls SetHeaderByNumberFunc.
func (mock *BlockPluginMock) SetHeaderByNumber(contextMoqParam context.Context, n int64, header *types.Header) error {
	if mock.SetHeaderByNumberFunc == nil {
		panic("BlockPluginMock.SetHeaderByNumberFunc: method is nil but BlockPlugin.SetHeaderByNumber was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		N               int64
		Header          *types.Header
	}{
		ContextMoqParam: contextMoqParam,
		N:               n,
		Header:          header,
	}
	mock.lockSetHeaderByNumber.Lock()
	mock.calls.SetHeaderByNumber = append(mock.calls.SetHeaderByNumber, callInfo)
	mock.lockSetHeaderByNumber.Unlock()
	return mock.SetHeaderByNumberFunc(contextMoqParam, n, header)
}

// SetHeaderByNumberCalls gets all the calls that were made to SetHeaderByNumber.
// Check the length with:
//
//	len(mockedBlockPlugin.SetHeaderByNumberCalls())
func (mock *BlockPluginMock) SetHeaderByNumberCalls() []struct {
	ContextMoqParam context.Context
	N               int64
	Header          *types.Header
} {
	var calls []struct {
		ContextMoqParam context.Context
		N               int64
		Header          *types.Header
	}
	mock.lockSetHeaderByNumber.RLock()
	calls = mock.calls.SetHeaderByNumber
	mock.lockSetHeaderByNumber.RUnlock()
	return calls
}
