// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"pkg.berachain.dev/polaris/eth/core"
	"pkg.berachain.dev/polaris/eth/core/precompile"
	"sync"
)

// Ensure, that PolarisHostChainMock does implement core.PolarisHostChain.
// If this is not the case, regenerate this file with moq.
var _ core.PolarisHostChain = &PolarisHostChainMock{}

// PolarisHostChainMock is a mock implementation of core.PolarisHostChain.
//
//	func TestSomethingThatUsesPolarisHostChain(t *testing.T) {
//
//		// make and configure a mocked core.PolarisHostChain
//		mockedPolarisHostChain := &PolarisHostChainMock{
//			GetBlockPluginFunc: func() core.BlockPlugin {
//				panic("mock out the GetBlockPlugin method")
//			},
//			GetConfigurationPluginFunc: func() core.ConfigurationPlugin {
//				panic("mock out the GetConfigurationPlugin method")
//			},
//			GetHistoricalPluginFunc: func() core.HistoricalPlugin {
//				panic("mock out the GetHistoricalPlugin method")
//			},
//			GetNewGasPluginFunc: func() core.GasPlugin {
//				panic("mock out the GetNewGasPlugin method")
//			},
//			GetPrecompilePluginFunc: func() precompile.Plugin {
//				panic("mock out the GetPrecompilePlugin method")
//			},
//			GetStatePluginFunc: func() core.StatePlugin {
//				panic("mock out the GetStatePlugin method")
//			},
//			GetTxPoolPluginFunc: func() core.TxPoolPlugin {
//				panic("mock out the GetTxPoolPlugin method")
//			},
//		}
//
//		// use mockedPolarisHostChain in code that requires core.PolarisHostChain
//		// and then make assertions.
//
//	}
type PolarisHostChainMock struct {
	// GetBlockPluginFunc mocks the GetBlockPlugin method.
	GetBlockPluginFunc func() core.BlockPlugin

	// GetConfigurationPluginFunc mocks the GetConfigurationPlugin method.
	GetConfigurationPluginFunc func() core.ConfigurationPlugin

	// GetHistoricalPluginFunc mocks the GetHistoricalPlugin method.
	GetHistoricalPluginFunc func() core.HistoricalPlugin

	// GetNewGasPluginFunc mocks the GetNewGasPlugin method.
	GetNewGasPluginFunc func() core.GasPlugin

	// GetPrecompilePluginFunc mocks the GetPrecompilePlugin method.
	GetPrecompilePluginFunc func() precompile.Plugin

	// GetStatePluginFunc mocks the GetStatePlugin method.
	GetStatePluginFunc func() core.StatePlugin

	// GetTxPoolPluginFunc mocks the GetTxPoolPlugin method.
	GetTxPoolPluginFunc func() core.TxPoolPlugin

	// calls tracks calls to the methods.
	calls struct {
		// GetBlockPlugin holds details about calls to the GetBlockPlugin method.
		GetBlockPlugin []struct {
		}
		// GetConfigurationPlugin holds details about calls to the GetConfigurationPlugin method.
		GetConfigurationPlugin []struct {
		}
		// GetHistoricalPlugin holds details about calls to the GetHistoricalPlugin method.
		GetHistoricalPlugin []struct {
		}
		// GetNewGasPlugin holds details about calls to the GetNewGasPlugin method.
		GetNewGasPlugin []struct {
		}
		// GetPrecompilePlugin holds details about calls to the GetPrecompilePlugin method.
		GetPrecompilePlugin []struct {
		}
		// GetStatePlugin holds details about calls to the GetStatePlugin method.
		GetStatePlugin []struct {
		}
		// GetTxPoolPlugin holds details about calls to the GetTxPoolPlugin method.
		GetTxPoolPlugin []struct {
		}
	}
	lockGetBlockPlugin         sync.RWMutex
	lockGetConfigurationPlugin sync.RWMutex
	lockGetHistoricalPlugin    sync.RWMutex
	lockGetNewGasPlugin        sync.RWMutex
	lockGetPrecompilePlugin    sync.RWMutex
	lockGetStatePlugin         sync.RWMutex
	lockGetTxPoolPlugin        sync.RWMutex
}

// GetBlockPlugin calls GetBlockPluginFunc.
func (mock *PolarisHostChainMock) GetBlockPlugin() core.BlockPlugin {
	if mock.GetBlockPluginFunc == nil {
		panic("PolarisHostChainMock.GetBlockPluginFunc: method is nil but PolarisHostChain.GetBlockPlugin was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetBlockPlugin.Lock()
	mock.calls.GetBlockPlugin = append(mock.calls.GetBlockPlugin, callInfo)
	mock.lockGetBlockPlugin.Unlock()
	return mock.GetBlockPluginFunc()
}

// GetBlockPluginCalls gets all the calls that were made to GetBlockPlugin.
// Check the length with:
//
//	len(mockedPolarisHostChain.GetBlockPluginCalls())
func (mock *PolarisHostChainMock) GetBlockPluginCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetBlockPlugin.RLock()
	calls = mock.calls.GetBlockPlugin
	mock.lockGetBlockPlugin.RUnlock()
	return calls
}

// GetConfigurationPlugin calls GetConfigurationPluginFunc.
func (mock *PolarisHostChainMock) GetConfigurationPlugin() core.ConfigurationPlugin {
	if mock.GetConfigurationPluginFunc == nil {
		panic("PolarisHostChainMock.GetConfigurationPluginFunc: method is nil but PolarisHostChain.GetConfigurationPlugin was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetConfigurationPlugin.Lock()
	mock.calls.GetConfigurationPlugin = append(mock.calls.GetConfigurationPlugin, callInfo)
	mock.lockGetConfigurationPlugin.Unlock()
	return mock.GetConfigurationPluginFunc()
}

// GetConfigurationPluginCalls gets all the calls that were made to GetConfigurationPlugin.
// Check the length with:
//
//	len(mockedPolarisHostChain.GetConfigurationPluginCalls())
func (mock *PolarisHostChainMock) GetConfigurationPluginCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetConfigurationPlugin.RLock()
	calls = mock.calls.GetConfigurationPlugin
	mock.lockGetConfigurationPlugin.RUnlock()
	return calls
}

// GetHistoricalPlugin calls GetHistoricalPluginFunc.
func (mock *PolarisHostChainMock) GetHistoricalPlugin() core.HistoricalPlugin {
	if mock.GetHistoricalPluginFunc == nil {
		panic("PolarisHostChainMock.GetHistoricalPluginFunc: method is nil but PolarisHostChain.GetHistoricalPlugin was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetHistoricalPlugin.Lock()
	mock.calls.GetHistoricalPlugin = append(mock.calls.GetHistoricalPlugin, callInfo)
	mock.lockGetHistoricalPlugin.Unlock()
	return mock.GetHistoricalPluginFunc()
}

// GetHistoricalPluginCalls gets all the calls that were made to GetHistoricalPlugin.
// Check the length with:
//
//	len(mockedPolarisHostChain.GetHistoricalPluginCalls())
func (mock *PolarisHostChainMock) GetHistoricalPluginCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetHistoricalPlugin.RLock()
	calls = mock.calls.GetHistoricalPlugin
	mock.lockGetHistoricalPlugin.RUnlock()
	return calls
}

// GetNewGasPlugin calls GetNewGasPluginFunc.
func (mock *PolarisHostChainMock) GetNewGasPlugin() core.GasPlugin {
	if mock.GetNewGasPluginFunc == nil {
		panic("PolarisHostChainMock.GetNewGasPluginFunc: method is nil but PolarisHostChain.GetNewGasPlugin was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetNewGasPlugin.Lock()
	mock.calls.GetNewGasPlugin = append(mock.calls.GetNewGasPlugin, callInfo)
	mock.lockGetNewGasPlugin.Unlock()
	return mock.GetNewGasPluginFunc()
}

// GetNewGasPluginCalls gets all the calls that were made to GetNewGasPlugin.
// Check the length with:
//
//	len(mockedPolarisHostChain.GetNewGasPluginCalls())
func (mock *PolarisHostChainMock) GetNewGasPluginCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetNewGasPlugin.RLock()
	calls = mock.calls.GetNewGasPlugin
	mock.lockGetNewGasPlugin.RUnlock()
	return calls
}

// GetPrecompilePlugin calls GetPrecompilePluginFunc.
func (mock *PolarisHostChainMock) GetPrecompilePlugin() precompile.Plugin {
	if mock.GetPrecompilePluginFunc == nil {
		panic("PolarisHostChainMock.GetPrecompilePluginFunc: method is nil but PolarisHostChain.GetPrecompilePlugin was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetPrecompilePlugin.Lock()
	mock.calls.GetPrecompilePlugin = append(mock.calls.GetPrecompilePlugin, callInfo)
	mock.lockGetPrecompilePlugin.Unlock()
	return mock.GetPrecompilePluginFunc()
}

// GetPrecompilePluginCalls gets all the calls that were made to GetPrecompilePlugin.
// Check the length with:
//
//	len(mockedPolarisHostChain.GetPrecompilePluginCalls())
func (mock *PolarisHostChainMock) GetPrecompilePluginCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetPrecompilePlugin.RLock()
	calls = mock.calls.GetPrecompilePlugin
	mock.lockGetPrecompilePlugin.RUnlock()
	return calls
}

// GetStatePlugin calls GetStatePluginFunc.
func (mock *PolarisHostChainMock) GetStatePlugin() core.StatePlugin {
	if mock.GetStatePluginFunc == nil {
		panic("PolarisHostChainMock.GetStatePluginFunc: method is nil but PolarisHostChain.GetStatePlugin was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetStatePlugin.Lock()
	mock.calls.GetStatePlugin = append(mock.calls.GetStatePlugin, callInfo)
	mock.lockGetStatePlugin.Unlock()
	return mock.GetStatePluginFunc()
}

// GetStatePluginCalls gets all the calls that were made to GetStatePlugin.
// Check the length with:
//
//	len(mockedPolarisHostChain.GetStatePluginCalls())
func (mock *PolarisHostChainMock) GetStatePluginCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetStatePlugin.RLock()
	calls = mock.calls.GetStatePlugin
	mock.lockGetStatePlugin.RUnlock()
	return calls
}

// GetTxPoolPlugin calls GetTxPoolPluginFunc.
func (mock *PolarisHostChainMock) GetTxPoolPlugin() core.TxPoolPlugin {
	if mock.GetTxPoolPluginFunc == nil {
		panic("PolarisHostChainMock.GetTxPoolPluginFunc: method is nil but PolarisHostChain.GetTxPoolPlugin was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetTxPoolPlugin.Lock()
	mock.calls.GetTxPoolPlugin = append(mock.calls.GetTxPoolPlugin, callInfo)
	mock.lockGetTxPoolPlugin.Unlock()
	return mock.GetTxPoolPluginFunc()
}

// GetTxPoolPluginCalls gets all the calls that were made to GetTxPoolPlugin.
// Check the length with:
//
//	len(mockedPolarisHostChain.GetTxPoolPluginCalls())
func (mock *PolarisHostChainMock) GetTxPoolPluginCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetTxPoolPlugin.RLock()
	calls = mock.calls.GetTxPoolPlugin
	mock.lockGetTxPoolPlugin.RUnlock()
	return calls
}
