name: daily

on:
  schedule:
    - cron: '0 0 * * *'  # This schedule runs the workflow daily at midnight UTC

jobs:
  docs:
    strategy:
      matrix:
        go-version: [1.21.6]
        python-version: [3.11.5]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout polaris
        uses: actions/checkout@v4
        with:
          path: polaris
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Forge doc
        run: |
          cd polaris
          forge doc
      - name: Checkout docs-monorepo
        uses: actions/checkout@v4
        with:
          repository: berachain/docs-monorepo
          token: ${{ secrets.DOCS_TOKEN }}
          path: docs-monorepo
          ref: main
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Generate docs
        run: |
          cd docs-monorepo
          pip install -r apps/digest/requirements.txt
          python apps/digest/main.py polaris
          git status
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update docs with Polaris changes
          repository: docs-monorepo
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
      